group: travis_latest
os: linux
dist: xenial  # focal
language: python
env:
  - UPGRADE_WEBPY=false
  - UPGRADE_WEBPY=true
python:
  - 2.7
  - 3.8
jobs:
  include:
    - name: "Python: 2.7 - Fail on Py3 only"
      script: bash scripts/pytests_failing_on_py3_only.sh
      python: 2.7
    - name: "Python: 3.8 - Fail on Py3 only"
      script: bash scripts/pytests_failing_on_py3_only.sh
      python: 3.8

    - name: "Python: 2.7 - Fail on Py2 and Py3"
      script: bash scripts/pytests_failing_on_py2_and_py3.sh
      python: 2.7
    - name: "Python: 3.8 - Fail on Py2 and Py3"
      script: bash scripts/pytests_failing_on_py2_and_py3.sh
      python: 3.8

    - name: "Python: 2.7 - Test Open Library"
      script: bash -x scripts/test-openlibrary.sh
      python: 2.7
    - name: "Python: 3.8 - Test Open Library"
      script: bash -x scripts/test-openlibrary.sh
      python: 3.8
      env: UPGRADE_WEBPY=true
  allow_failures:
    - script: bash scripts/pytests_failing_on_py2_and_py3.sh
install:
  - pip install codespell flake8 pytest psycopg2
  - pip install -r requirements.txt
  - if [[ "$UPGRADE_WEBPY" == true ]]; then pip install --upgrade web.py; fi
services:
  - postgresql
before_script:
  - psql -c 'create database infobase_test;' -U postgres
  - codespell . --ignore-words-list=ba,referer --quiet-level=2
  # stop the build if there are Python syntax errors or undefined names
  - flake8 . --count --select=E9,F401,F63,F7,F82 --show-source --statistics
  # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
script:
  - source scripts/run_pytests.sh
  - source scripts/run_doctests.sh
notifications:
  on_success: change
  on_failure: change  # `always` will be the setting once code changes slow down
