group: travis_latest
os: linux
dist: xenial  # focal
language: python
python:
  - 3.9
jobs:
  include:
    - name: "Fail on Py3 only"
      script: bash scripts/pytests_failing_on_py3_only.sh
    - name: "Fail on Py2 and Py3"
      script: bash scripts/pytests_failing_on_py2_and_py3.sh
    - name: "Test Open Library"
      script: bash -x scripts/test-openlibrary.sh
  allow_failures:
    - script: bash scripts/pytests_failing_on_py2_and_py3.sh
install:
  - pip install codespell flake8 pytest psycopg2
  - pip install -r requirements.txt
services:
  - postgresql
before_script:
  - psql -c 'create database infobase_test;' -U postgres
  - codespell . --ignore-words-list=ba,referer --quiet-level=2
  # stop the build if there are Python syntax errors or undefined names
  - flake8 . --count --select=E9,F401,F63,F7,F82 --show-source --statistics
  # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
script:
  - pytest infogami -s
  - pytest tests
  - pytest test
  - source scripts/run_doctests.sh
notifications:
  email:
    on_success: change
    on_failure: change  # `always` will be the setting once code changes slow down
